basePath: /api/v1
info:
  contact:
    email: quangdangfit@gmail.com
    name: Quang Dang
  description: Swagger API for GoShop.
  license:
    name: MIT
    url: https://github.com/MartinHeinz/go-project-blueprint/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: GoShop Swagger API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
