definitions:
  paging.Pagination:
    properties:
      current_page:
        type: integer
      limit:
        type: integer
      skip:
        type: integer
      total:
        type: integer
      total_page:
        type: integer
    type: object
  serializers.ListProductRes:
    properties:
      pagination:
        $ref: '#/definitions/paging.Pagination'
      products:
        items:
          $ref: '#/definitions/serializers.Product'
        type: array
    type: object
  serializers.Product:
    properties:
      active:
        type: boolean
      code:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/products:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializers.ListProductRes'
      security:
      - ApiKeyAuth: []
      summary: Get list products
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializers.Product'
      security:
      - ApiKeyAuth: []
      summary: create product
  /api/v1/products/{id}:
    get:
      parameters:
      - description: Product UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializers.Product'
      security:
      - ApiKeyAuth: []
      summary: Get get product by uuid
    put:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializers.Product'
      security:
      - ApiKeyAuth: []
      summary: update product
swagger: "2.0"
